PROC LOGISTIC ;
  CLASS A B C D E F G H I J K Q29 Q3 Q2 Q1 Q4;
  MODEL Y=A B C D E F G H I J K Q29 Q3 Q2 Q1 Q4/SCALE=NONE AGGREGATE;
  OUTPUT OUT=prob pred=p;
RUN;


PROC LOGISTIC ;
  CLASS A B C D  G I  K Q29 ;
  MODEL Y=A B C D  G  I  K Q29 /SCALE=NONE AGGREGATE;
  OUTPUT OUT=prob pred=p;
RUN;
PROC PRINT data=prob;
RUN;
